version: ~> 1.0

language: node_js
node_js:
  - "14"

before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - node --version
  - npm --version
  - npx --version
script:
  - npm test


